### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by artpxl** [Seaony/Laradmin#1]
Hello

How can i install this?
Thanks

**Comment by Seaony** [comment]
hello,this is a private project，I have not done enough preparatory work to ensure that it can work properly on your computer,but，if you want use the project，you can clone to your  computer and executed in your cmd
```php
composer install
composer migrate
php artisan db:seed
```

then visit this url to admin system: http://yourdomain.com/admin

I'm glad you want to use my project, I will perfect it as soon as possible and provide detailed instructions  :)

**Comment by artpxl** [comment]
going to try. Thanks!
